//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMENsoft_OTOPARK
{
    using System;
    using System.Collections.Generic;
    
    public partial class giri
    {
        public int ID { get; set; }
        public string kullanici { get; set; }
        public string sifre { get; set; }
        public string eposta { get; set; }
    }
}
