//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMENsoft_OTOPARK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konum
    {
        public int Id { get; set; }
        public string a_plaka { get; set; }
        public string konum1 { get; set; }
    
        public virtual Arac Arac { get; set; }
    }
}
