//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMENsoft_OTOPARK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RMENDatabaseEntities : DbContext
    {
        public RMENDatabaseEntities()
            : base("name=RMENDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arac> Aracs { get; set; }
        public virtual DbSet<bo> bos { get; set; }
        public virtual DbSet<dolu> dolus { get; set; }
        public virtual DbSet<giri> giris { get; set; }
        public virtual DbSet<Konum> Konums { get; set; }
        public virtual DbSet<logKayit> logKayits { get; set; }
        public virtual DbSet<Tarih> Tarihs { get; set; }
        public virtual DbSet<veriDepo> veriDepoes { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
    }
}
