//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMENsoft_OTOPARK
{
    using System;
    using System.Collections.Generic;
    
    public partial class veriDepo
    {
        public int Id { get; set; }
        public string TC { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string Tel { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Renk { get; set; }
        public string Konum { get; set; }
        public string Giris { get; set; }
        public string Cikis { get; set; }
        public Nullable<double> Ucret { get; set; }
    }
}
